version: "3.9"

services:
  resource-server:
    build:
      context: ../resource-server
    container_name: resource-server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped
