# Perfil OKR5: datasource embebido para permitir arrancar sin BD externa
spring.datasource.url=jdbc:h2:mem:okr5;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

# Actuator para observabilidad
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

# (Opcional) caché de health para mejorar latencia (servirá para api%)
management.endpoint.health.cache.time-to-live=10s
spring.application.name=resource-server
management.metrics.tags.application=${spring.application.name}

# Exponer endpoints de Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# Habilitar histogramas (necesario para http_server_requests_seconds_bucket)
management.metrics.distribution.percentiles-histogram.http.server.requests=true
