name: CD

on:
  push:
    branches: [ develop ]

jobs:
  build-and-push-resource-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login en GHCR (PAT classic)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: adrianjj2003
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push imagen
        uses: docker/build-push-action@v6
        with:
          context: ./resource-server
          push: true
          tags: |
            ghcr.io/adrianjj2003/resource-server:${{ github.sha }}
            ghcr.io/adrianjj2003/resource-server:latest

      - name: Escaneo de vulnerabilidades (post-push)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/adrianjj2003/resource-server:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: "0"
