name: CD

on:
  push:
    branches: [ develop ]

jobs:
  build-and-push-resource-server:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login en GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build imagen Docker resource-server
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/resource-server:latest \
            ./resource-server

      - name: Push imagen a GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/resource-server:latest
